
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/,http://localhost:9002/eureka/,http://localhost:9003/eureka/

server:
  port: 8795

spring:
  application:
    name: service-image

image:
  serv: http://52.197.128.235:2018/
  name1: D1.jpg

