version: '3'
services:
    time:
        build: ./
        deploy:
          mode: replicated
          replicas: 3
        networks:
            - spring_cloud
        command: ["java",
        "-Deureka.client.serviceUrl.defaultZone=http://eureka1:8000/eureka,http://eureka2:8000/eureka,http://eureka3:8000/eureka",
        "-jar","time.jar"]
networks:
  spring_cloud:
    external:
      name: spring_cloud
