version: '3'
services:
    weather:
        build:
            context: ./
            args:
              JAR_FILE: ./weather/target/weather-0.0.1-SNAPSHOT.jar
        networks:
            - spring_cloud
        ports:
            - "8796:8796"
        environment:
            EUREKA_PEERS: http://eureka1:8000/eureka,http://eureka2:8000/eureka,http://eureka3:8000/eureka

networks:
    spring_cloud:
        external:
            name: spring_cloud
