
eureka:
  client:
    serviceUrl:
      defaultZone: http://66.42.42.84:9001/eureka/,http://66.42.42.84:9002/eureka/,http://66.42.42.84:9003/eureka/

server:
  port: 8080

spring:
  application:
    name: web-image
