version: '3'
services:
    gateway:
        build: ./
        ports:
            - "8920:8790"
        networks:
            - spring_cloud

networks:
  spring_cloud:
      external:
          name: spring_cloud
