version: '3'
services:

    gatewayfilter:
        build:
            context: ./
            args:
              JAR_FILE: ./target/gatewayfilter-0.0.1-SNAPSHOT.jar
        ports:
          - "9000:8790"
        networks:
            - spring_cloud

networks:
    spring_cloud:
        external:
            name: spring_cloud
